# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Vicky
tagline:             'My first blog'
description:         'R-Ladies event'
url:                 http://blue-moon22.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vicky Butt
  url:               https://twitter.com/victoriabutt1
  email:             bluemoon22@fakeemail.com

# Custom vars
version:             1.0.0
